#import "Album.h"
#import "ARAddToAlbumViewController.h"

Album *albumThatIsEditableInContext(BOOL editable, NSManagedObjectContext *context);
Album *folioGeneratedAlbumInContext(NSManagedObjectContext *context);

SpecBegin(ARAddToAlbumViewController);

describe(@"init", ^{

    it(@"should have albums + 1 rows", ^{

        NSManagedObjectContext *context = [CoreDataManager stubbedManagedObjectContext];
        albumThatIsEditableInContext(YES, context);

        ARAddToAlbumViewController *controller = [[ARAddToAlbumViewController alloc] initWithManagedObjectContext:context];
        NSInteger count = [controller tableView:controller.tableView numberOfRowsInSection:0];
        expect(count).to.equal(2);
    });
    
    it(@"don't show sync info when there are no CMS albums", ^{
        NSManagedObjectContext *context = [CoreDataManager stubbedManagedObjectContext];
        albumThatIsEditableInContext(YES, context);
        albumThatIsEditableInContext(YES, context);
        albumThatIsEditableInContext(YES, context);
        
        ARAddToAlbumViewController *controller = [[ARAddToAlbumViewController alloc] initWithManagedObjectContext:context];
        controller.view.frame = (CGRect){ CGPointZero, [controller preferredContentSize]};
        expect(controller).to.haveValidSnapshot();
    });
    
    it(@"shows sync info when there are CMS albums", ^{
        NSManagedObjectContext *context = [CoreDataManager stubbedManagedObjectContext];
        albumThatIsEditableInContext(YES, context);
        albumThatIsEditableInContext(NO, context);
        
        ARAddToAlbumViewController *controller = [[ARAddToAlbumViewController alloc] initWithManagedObjectContext:context];
        controller.view.frame = (CGRect){ CGPointZero, [controller preferredContentSize]};
        expect(controller).to.haveValidSnapshot();
    });
    
    it(@"does not show sync info for albums generated by folio", ^{
        NSManagedObjectContext *context = [CoreDataManager stubbedManagedObjectContext];
        albumThatIsEditableInContext(YES, context);
        albumThatIsEditableInContext(YES, context);
        folioGeneratedAlbumInContext(context);
        
        ARAddToAlbumViewController *controller = [[ARAddToAlbumViewController alloc] initWithManagedObjectContext:context];
        controller.view.frame = (CGRect){ CGPointZero, [controller preferredContentSize]};
        expect(controller).to.haveValidSnapshot();
    });

});

SpecEnd

    Album *
    albumThatIsEditableInContext(BOOL editable, NSManagedObjectContext *context)
{
    Album *album = [Album objectInContext:context];
    album.editable = @(editable);
    return album;
}

Album *
folioGeneratedAlbumInContext(NSManagedObjectContext *context)
{
    Album *album = [Album objectInContext:context];
    album.editable = @NO;
    album.slug = @"for_sale_works";
    return album;
}
