email 'it@artsymail.com'

app_identifier "sy.art.folio"
apple_id "504862164"


screenshots_path "./config/deliver/screenshots/"
version '2.1.0'
config_json_folder './config/deliver'


ipa do
    changelog({
        "en-US" => "Your mobile inventory now available on any iOS device:
    •    Introducing Folio for iPhone
    •    Major improvements in sync process, email design, and albums
    •    Updated flow for album creation and editing
    •    More Bug fixes"
    })

    system("ipa build") # build your project using Shenzhen
    "./energy.ipa" # Tell 'Deliver' where it can find the finished ipa file
end

success do
  system("say 'Successfully deployed a new version.'")
end
