devices ["iPhone 6", "iPhone 6 Plus", "iPhone 5s", "iPhone 4s",  "iPad Retina"]
languages 'en-US'

screenshots_path "screenshots"
js_file 'snapshots/snapshot.js'

scheme 'ArtsyFolio'
project_path '../Artsy Folio.xcworkspace'

unless File.exist? "set_up_db/logged_in_snapshots.sqlite"
  puts "Expected a sqlite database of a logged in user at `set_up_db/logged_in_snapshots.sqlite`.".red
  exit
end

setup_for_device_change do |device, udid, language|
  puts "Running #{language} on #{device}"
end
