#!/usr/bin/env bash
set -euxo pipefail


# Get fonts from eigen s3 bucket
aws s3 cp s3://artsy-citadel/eigen/fonts.tar.gz ./fonts.tar.gz

# Extract fonts
tar -xvzf fonts.tar.gz -C ./android/app/src/main/assets/fonts

# Cleanup
rm -rf ./fonts.tar.gz
