#!/bin/bash

# This assumes you have general prerequisites installed as by:
# https://github.com/artsy/potential/blob/master/scripts/setup

# Exit if any subcommand fails
set -e

echo "Downloading .env.shared file..."
if ! aws s3 cp s3://artsy-citadel/dev/.env.energy .env.shared; then
  echo "Unable to download shared config from s3"
  echo "This is expected for open source contributors. We will work on adding support for OSS soon"
  echo "If you work at Artsy, please check your s3 access."
  cp .env.oss .env.shared
fi

if [[ ! -e ".env" ]]; then
  echo "Initializing .env from .env.example (for custom configuration)..."
  cat .env.example > .env
fi

if [[ -e ".env.dev" ]]; then
  echo "Removing existing .env.dev file"
  rm .env.dev
fi

echo "Creating .env.dev from .env and .dev.shared..."
awk 1 .env.shared .env > .env.dev

echo "Preparing environment variables completed!"
